// Code generated by protoc-gen-go. DO NOT EDIT.
// source: content/v1/content.proto

/*
Package contentv1 is a generated protocol buffer package.

It is generated from these files:

	content/v1/content.proto

It has these top-level messages:

	CreatePostRequest
	CreatePostResponse
	ListPostsRequest
	ListPostsResponse
	GetPostRequest
	GetPostResponse
	SearchPostsRequest
	SearchPostsResponse
	Post
*/
package contentv1

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// CreatePostRequest 创建请求
type CreatePostRequest struct {
	Company    string `protobuf:"bytes,1,opt,name=company" json:"company,omitempty"`
	CityCode   string `protobuf:"bytes,2,opt,name=city_code,json=cityCode" json:"city_code,omitempty"`
	CityName   string `protobuf:"bytes,3,opt,name=city_name,json=cityName" json:"city_name,omitempty"`
	Content    string `protobuf:"bytes,4,opt,name=content" json:"content,omitempty"`
	OccurredAt int64  `protobuf:"varint,5,opt,name=occurred_at,json=occurredAt" json:"occurred_at,omitempty"`
}

func (m *CreatePostRequest) Reset()                    { *m = CreatePostRequest{} }
func (m *CreatePostRequest) String() string            { return proto.CompactTextString(m) }
func (*CreatePostRequest) ProtoMessage()               {}
func (*CreatePostRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *CreatePostRequest) GetCompany() string {
	if m != nil {
		return m.Company
	}
	return ""
}

func (m *CreatePostRequest) GetCityCode() string {
	if m != nil {
		return m.CityCode
	}
	return ""
}

func (m *CreatePostRequest) GetCityName() string {
	if m != nil {
		return m.CityName
	}
	return ""
}

func (m *CreatePostRequest) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *CreatePostRequest) GetOccurredAt() int64 {
	if m != nil {
		return m.OccurredAt
	}
	return 0
}

// CreatePostResponse 创建响应
type CreatePostResponse struct {
	PostId    string `protobuf:"bytes,1,opt,name=post_id,json=postId" json:"post_id,omitempty"`
	CreatedAt int64  `protobuf:"varint,2,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
}

func (m *CreatePostResponse) Reset()                    { *m = CreatePostResponse{} }
func (m *CreatePostResponse) String() string            { return proto.CompactTextString(m) }
func (*CreatePostResponse) ProtoMessage()               {}
func (*CreatePostResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *CreatePostResponse) GetPostId() string {
	if m != nil {
		return m.PostId
	}
	return ""
}

func (m *CreatePostResponse) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

// ListPostsRequest 列表请求
type ListPostsRequest struct {
	CityCode string `protobuf:"bytes,1,opt,name=city_code,json=cityCode" json:"city_code,omitempty"`
	Page     int32  `protobuf:"varint,2,opt,name=page" json:"page,omitempty"`
	PageSize int32  `protobuf:"varint,3,opt,name=page_size,json=pageSize" json:"page_size,omitempty"`
}

func (m *ListPostsRequest) Reset()                    { *m = ListPostsRequest{} }
func (m *ListPostsRequest) String() string            { return proto.CompactTextString(m) }
func (*ListPostsRequest) ProtoMessage()               {}
func (*ListPostsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ListPostsRequest) GetCityCode() string {
	if m != nil {
		return m.CityCode
	}
	return ""
}

func (m *ListPostsRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListPostsRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

// ListPostsResponse 列表响应
type ListPostsResponse struct {
	Posts    []*Post `protobuf:"bytes,1,rep,name=posts" json:"posts,omitempty"`
	Total    int32   `protobuf:"varint,2,opt,name=total" json:"total,omitempty"`
	Page     int32   `protobuf:"varint,3,opt,name=page" json:"page,omitempty"`
	PageSize int32   `protobuf:"varint,4,opt,name=page_size,json=pageSize" json:"page_size,omitempty"`
}

func (m *ListPostsResponse) Reset()                    { *m = ListPostsResponse{} }
func (m *ListPostsResponse) String() string            { return proto.CompactTextString(m) }
func (*ListPostsResponse) ProtoMessage()               {}
func (*ListPostsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ListPostsResponse) GetPosts() []*Post {
	if m != nil {
		return m.Posts
	}
	return nil
}

func (m *ListPostsResponse) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *ListPostsResponse) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ListPostsResponse) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

// GetPostRequest 详情请求
type GetPostRequest struct {
	PostId string `protobuf:"bytes,1,opt,name=post_id,json=postId" json:"post_id,omitempty"`
}

func (m *GetPostRequest) Reset()                    { *m = GetPostRequest{} }
func (m *GetPostRequest) String() string            { return proto.CompactTextString(m) }
func (*GetPostRequest) ProtoMessage()               {}
func (*GetPostRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GetPostRequest) GetPostId() string {
	if m != nil {
		return m.PostId
	}
	return ""
}

// GetPostResponse 详情响应
type GetPostResponse struct {
	Post *Post `protobuf:"bytes,1,opt,name=post" json:"post,omitempty"`
}

func (m *GetPostResponse) Reset()                    { *m = GetPostResponse{} }
func (m *GetPostResponse) String() string            { return proto.CompactTextString(m) }
func (*GetPostResponse) ProtoMessage()               {}
func (*GetPostResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GetPostResponse) GetPost() *Post {
	if m != nil {
		return m.Post
	}
	return nil
}

// SearchPostsRequest 搜索请求
type SearchPostsRequest struct {
	Keyword  string `protobuf:"bytes,1,opt,name=keyword" json:"keyword,omitempty"`
	CityCode string `protobuf:"bytes,2,opt,name=city_code,json=cityCode" json:"city_code,omitempty"`
	Page     int32  `protobuf:"varint,3,opt,name=page" json:"page,omitempty"`
	PageSize int32  `protobuf:"varint,4,opt,name=page_size,json=pageSize" json:"page_size,omitempty"`
}

func (m *SearchPostsRequest) Reset()                    { *m = SearchPostsRequest{} }
func (m *SearchPostsRequest) String() string            { return proto.CompactTextString(m) }
func (*SearchPostsRequest) ProtoMessage()               {}
func (*SearchPostsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *SearchPostsRequest) GetKeyword() string {
	if m != nil {
		return m.Keyword
	}
	return ""
}

func (m *SearchPostsRequest) GetCityCode() string {
	if m != nil {
		return m.CityCode
	}
	return ""
}

func (m *SearchPostsRequest) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *SearchPostsRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

// SearchPostsResponse 搜索响应
type SearchPostsResponse struct {
	Posts    []*Post `protobuf:"bytes,1,rep,name=posts" json:"posts,omitempty"`
	Total    int32   `protobuf:"varint,2,opt,name=total" json:"total,omitempty"`
	Page     int32   `protobuf:"varint,3,opt,name=page" json:"page,omitempty"`
	PageSize int32   `protobuf:"varint,4,opt,name=page_size,json=pageSize" json:"page_size,omitempty"`
}

func (m *SearchPostsResponse) Reset()                    { *m = SearchPostsResponse{} }
func (m *SearchPostsResponse) String() string            { return proto.CompactTextString(m) }
func (*SearchPostsResponse) ProtoMessage()               {}
func (*SearchPostsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *SearchPostsResponse) GetPosts() []*Post {
	if m != nil {
		return m.Posts
	}
	return nil
}

func (m *SearchPostsResponse) GetTotal() int32 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *SearchPostsResponse) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *SearchPostsResponse) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

// Post 帖子
type Post struct {
	Id         string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Company    string `protobuf:"bytes,2,opt,name=company" json:"company,omitempty"`
	CityCode   string `protobuf:"bytes,3,opt,name=city_code,json=cityCode" json:"city_code,omitempty"`
	CityName   string `protobuf:"bytes,4,opt,name=city_name,json=cityName" json:"city_name,omitempty"`
	Content    string `protobuf:"bytes,5,opt,name=content" json:"content,omitempty"`
	OccurredAt int64  `protobuf:"varint,6,opt,name=occurred_at,json=occurredAt" json:"occurred_at,omitempty"`
	CreatedAt  int64  `protobuf:"varint,7,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
}

func (m *Post) Reset()                    { *m = Post{} }
func (m *Post) String() string            { return proto.CompactTextString(m) }
func (*Post) ProtoMessage()               {}
func (*Post) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Post) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Post) GetCompany() string {
	if m != nil {
		return m.Company
	}
	return ""
}

func (m *Post) GetCityCode() string {
	if m != nil {
		return m.CityCode
	}
	return ""
}

func (m *Post) GetCityName() string {
	if m != nil {
		return m.CityName
	}
	return ""
}

func (m *Post) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

func (m *Post) GetOccurredAt() int64 {
	if m != nil {
		return m.OccurredAt
	}
	return 0
}

func (m *Post) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func init() {
	proto.RegisterType((*CreatePostRequest)(nil), "content.v1.CreatePostRequest")
	proto.RegisterType((*CreatePostResponse)(nil), "content.v1.CreatePostResponse")
	proto.RegisterType((*ListPostsRequest)(nil), "content.v1.ListPostsRequest")
	proto.RegisterType((*ListPostsResponse)(nil), "content.v1.ListPostsResponse")
	proto.RegisterType((*GetPostRequest)(nil), "content.v1.GetPostRequest")
	proto.RegisterType((*GetPostResponse)(nil), "content.v1.GetPostResponse")
	proto.RegisterType((*SearchPostsRequest)(nil), "content.v1.SearchPostsRequest")
	proto.RegisterType((*SearchPostsResponse)(nil), "content.v1.SearchPostsResponse")
	proto.RegisterType((*Post)(nil), "content.v1.Post")
}

func init() { proto.RegisterFile("content/v1/content.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 532 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x54, 0xc1, 0x6e, 0xd3, 0x40,
	0x10, 0x95, 0x1d, 0x3b, 0x6e, 0x26, 0x52, 0x68, 0x17, 0x24, 0x2c, 0x97, 0xd0, 0xc8, 0x42, 0x28,
	0x5c, 0x62, 0x12, 0x0e, 0x1c, 0x38, 0xb5, 0x39, 0x00, 0xa2, 0xaa, 0x90, 0x73, 0xe3, 0x62, 0x36,
	0xeb, 0x05, 0xac, 0x10, 0xaf, 0xf1, 0x6e, 0x82, 0x52, 0x71, 0x42, 0x7c, 0x09, 0xbf, 0xc1, 0x95,
	0x0f, 0x43, 0x5e, 0xaf, 0x1d, 0xdb, 0xad, 0x23, 0x71, 0xea, 0x29, 0x9e, 0x7d, 0x93, 0x37, 0x6f,
	0x66, 0xe7, 0x2d, 0xd8, 0x84, 0xc5, 0x82, 0xc6, 0xc2, 0xdb, 0x4e, 0x3d, 0xf5, 0x39, 0x49, 0x52,
	0x26, 0x18, 0x82, 0x22, 0xdc, 0x4e, 0xdd, 0xdf, 0x1a, 0x9c, 0xcc, 0x53, 0x8a, 0x05, 0x7d, 0xcf,
	0xb8, 0xf0, 0xe9, 0xb7, 0x0d, 0xe5, 0x02, 0xd9, 0x60, 0x11, 0xb6, 0x4e, 0x70, 0xbc, 0xb3, 0xb5,
	0x91, 0x36, 0xee, 0xf9, 0x45, 0x88, 0x4e, 0xa1, 0x47, 0x22, 0xb1, 0x0b, 0x08, 0x0b, 0xa9, 0xad,
	0x4b, 0xec, 0x28, 0x3b, 0x98, 0xb3, 0x90, 0x96, 0x60, 0x8c, 0xd7, 0xd4, 0xee, 0xec, 0xc1, 0x2b,
	0xbc, 0xa6, 0x39, 0xa7, 0xac, 0x6b, 0x1b, 0x05, 0xa7, 0x0c, 0xd1, 0x19, 0xf4, 0x19, 0x21, 0x9b,
	0x34, 0xa5, 0x61, 0x80, 0x85, 0x6d, 0x8e, 0xb4, 0x71, 0xc7, 0x87, 0xe2, 0xe8, 0x5c, 0xb8, 0x97,
	0x80, 0xaa, 0x1a, 0x79, 0xc2, 0x62, 0x4e, 0xd1, 0x43, 0xb0, 0x12, 0xc6, 0x45, 0x10, 0x85, 0x4a,
	0x64, 0x37, 0x0b, 0xdf, 0x86, 0x68, 0x08, 0x40, 0x64, 0xba, 0xa4, 0xd3, 0x25, 0x5d, 0x4f, 0x9d,
	0x9c, 0x0b, 0xf7, 0x23, 0x1c, 0x5f, 0x46, 0x5c, 0x64, 0x5c, 0xbc, 0x68, 0xb8, 0xd6, 0x96, 0xd6,
	0x68, 0x0b, 0x81, 0x91, 0xe0, 0xcf, 0x79, 0xbb, 0xa6, 0x2f, 0xbf, 0xb3, 0x3f, 0x64, 0xbf, 0x01,
	0x8f, 0xae, 0xf3, 0x56, 0x4d, 0xff, 0x28, 0x3b, 0x58, 0x44, 0xd7, 0xd4, 0xfd, 0xa9, 0xc1, 0x49,
	0xa5, 0x84, 0xd2, 0xfb, 0x14, 0xcc, 0x4c, 0x20, 0xb7, 0xb5, 0x51, 0x67, 0xdc, 0x9f, 0x1d, 0x4f,
	0xf6, 0xd7, 0x30, 0x91, 0x8d, 0xe5, 0x30, 0x7a, 0x00, 0xa6, 0x60, 0x02, 0x7f, 0x55, 0xf5, 0xf2,
	0xa0, 0x14, 0xd1, 0x69, 0x13, 0x61, 0x34, 0x44, 0x3c, 0x83, 0xc1, 0x6b, 0x2a, 0xaa, 0xb7, 0xda,
	0x36, 0x30, 0xf7, 0x25, 0xdc, 0x2b, 0x53, 0x95, 0xd8, 0x27, 0x60, 0x64, 0xa0, 0x4c, 0xbc, 0x4d,
	0xab, 0x44, 0xdd, 0x1f, 0x80, 0x16, 0x14, 0xa7, 0xe4, 0x4b, 0x6d, 0x98, 0x36, 0x58, 0x2b, 0xba,
	0xfb, 0xce, 0xd2, 0xa2, 0x4e, 0x11, 0x1e, 0xde, 0x9e, 0xff, 0xee, 0xf0, 0x97, 0x06, 0xf7, 0x6b,
	0xe5, 0xef, 0x66, 0xd0, 0x7f, 0x35, 0x30, 0x32, 0x5a, 0x34, 0x00, 0xbd, 0x1c, 0xad, 0x1e, 0x85,
	0x55, 0x17, 0xe9, 0x07, 0x5c, 0xd4, 0x39, 0xe4, 0x22, 0xa3, 0xdd, 0x45, 0xe6, 0x41, 0x17, 0x75,
	0x9b, 0x2e, 0x6a, 0xd8, 0xc2, 0x6a, 0xd8, 0x62, 0xf6, 0x47, 0x87, 0xc1, 0x3c, 0xe7, 0x5a, 0xd0,
	0x74, 0x1b, 0x11, 0x8a, 0xde, 0x01, 0xec, 0x7d, 0x87, 0x86, 0xd5, 0x39, 0xde, 0x78, 0x33, 0x9c,
	0xc7, 0x6d, 0xb0, 0xba, 0x95, 0x37, 0xd0, 0x2b, 0x3d, 0x81, 0x1e, 0x55, 0x93, 0x9b, 0x6e, 0x74,
	0x86, 0x2d, 0xa8, 0x62, 0xba, 0x00, 0x4b, 0xad, 0x2b, 0x72, 0xaa, 0x99, 0xf5, 0x75, 0x77, 0x4e,
	0x6f, 0xc5, 0x14, 0xc7, 0x15, 0xf4, 0x2b, 0xab, 0x83, 0x6a, 0xe2, 0x6f, 0xae, 0xb4, 0x73, 0xd6,
	0x8a, 0xe7, 0x7c, 0x17, 0xb3, 0x0f, 0xcf, 0x3f, 0x6d, 0xc8, 0x2a, 0x58, 0x32, 0xce, 0xbd, 0x25,
	0x26, 0x2b, 0x1a, 0x87, 0x1e, 0x4e, 0x22, 0x4f, 0x3e, 0xb9, 0xde, 0xfe, 0x2d, 0x7e, 0xa5, 0x3e,
	0xb7, 0xd3, 0x65, 0x57, 0x62, 0x2f, 0xfe, 0x05, 0x00, 0x00, 0xff, 0xff, 0x2f, 0x86, 0x03, 0x7a,
	0xaa, 0x05, 0x00, 0x00,
}
